import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans, Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SideBar, SidebarSection } from "@/components/organism/Sidebar/SideBar";
import { Calendar1Icon, UsersRoundIcon } from "lucide-react";

const manropeHeading = Manrope({subsets:['latin'],variable:'--font-heading'});

const dmSans = DM_Sans({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sections: SidebarSection[] = [
  {
    label: "Principal",
    buttons: [
      {
        icon: <Calendar1Icon size={16} />,
        label: "Agenda",
        url: "/agenda",
        params: {
          "Teste": { aoba: 2 }
        }
      },
      {
        icon: <UsersRoundIcon size={16} />,
        label: "Clientes",
        url: "/customers",
        params: {
          "Teste": { aoba: 2 }
        }
      }
    ]
  }
]

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-screen", "antialiased", geistSans.variable, geistMono.variable, "font-sans", dmSans.variable, manropeHeading.variable)}
    >
      <body className="min-h-full h-screen flex w-full">
          <SideBar sections={sections} />
          {children}
      </body>
    </html>
  );
}
