spring.config.import=optional:file:.env[.properties]

spring.application.name=schedule-manager

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5434}/${POSTGRES_DB:schedule_manager_db}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${HIBERNATE-DLL-AUTO:create-drop}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true